openapi: 3.1.0
info:
  title: OneCell ‚Üí LIS Integration API
  version: 1.10.0
  license:
    name: Commercial
    url: https://onecell.ai/#api-license
  description: |-
    –î–∞–Ω–Ω—ã–π –¥–æ–º—É–º–µ–Ω—Ç –æ–ø–∏—Å—ã–≤–∞–µ—Ç –∫–æ–Ω–µ—á–Ω—ã–µ —Ç–æ—á–∫–∏ (endpoints), 
    –∫–æ—Ç–æ—Ä—ã–µ –¥–æ–ª–∂–µ–Ω –ø–æ–¥–¥–µ—Ä–∂–∏–≤–∞—Ç—å **–õ–ò–°** —Å–æ —Å–≤–æ–µ–π —Å—Ç–æ—Ä–æ–Ω—ã –¥–ª—è –∏–Ω—Ç–µ–≥—Ä–∞—Ü–∏–∏ —Å **–ü–ê–ö–° OneCell**.

    OneCell –±—É–¥–µ—Ç –¥–µ–ª–∞—Ç—å –∑–∞–ø—Ä–æ—Å—ã –Ω–∞ –¥–∞–Ω–Ω—ã–µ –∫–æ–Ω–µ—á–Ω—ã–µ —Ç–æ—á–∫–∏ –¥–ª—è –ø–µ—Ä–µ–¥–∞—á–∏ –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏–∏ –∏–∑ **–ü–ê–ö–°** –≤ **–õ–ò–°**.
servers:
  - url: https://lis.acme.corp
security:
  - BasicAuth: []
paths:
  /case/search:
    post:
      summary: –ü–æ–ª—É—á–µ–Ω–∏–µ –Ω–∞–±–æ—Ä–∞ —Å–ª—É—á–∞–µ–≤ –∏–∑ LIS –ø–æ –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–∞–º
      description: |
        –ü–æ–ª—É—á–µ–Ω–∏–µ –Ω–∞–±–æ—Ä–∞ —Å–ª—É—á–∞–µ–≤ –∏–∑ LIS –¥–ª—è –∏—Ö –æ–±–Ω–æ–≤–ª–µ–Ω–∏—è –Ω–∞ —Å—Ç–æ—Ä–æ–Ω–µ PACS, –ª–∏–±–æ –¥–ª—è –∏—Ö –≤—ã–≥—Ä—É–∑–∫–∏ –≤ PACS –ø–æ –µ–≥–æ –∏–Ω–∏—Ü–∏–∞—Ç–∏–≤–µ.

        –ü—Ä–∏ –ø–æ–∏—Å–∫–µ –≤—Å–µ–≥–¥–∞ –ø–µ—Ä–µ–¥–∞—ë—Ç—Å—è –º–∞—Å—Å–∏–≤, –≥–¥–µ –∫–∞–∂–¥—ã–π —ç–ª–µ–º–µ–Ω—Ç –æ–¥–∏–Ω –∏–ª–∏ –Ω–µ—Å–∫–æ–ª—å–∫–æ –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–≤ –¥–ª—è —Ñ–∏–ª—å—Ç—Ä–∞—Ü–∏–∏.

        –ü—Ä–∏ –ø–µ—Ä–µ–¥–∞—á–µ –Ω–µ—Å–∫–æ–ª—å–∫–∏—Ö —É—Å–ª–æ–≤–∏–π –ø–æ–∏—Å–∫–∞ –≤ —Ä–∞–º–∫–∞—Ö –æ–¥–Ω–æ–≥–æ –æ–±—ä–µ–∫—Ç–∞, —Å–µ—Ä–≤–µ—Ä –¥–æ–ª–∂–µ–Ω –∏—Å–∫–∞—Ç—å –æ–±—ä–µ–∫—Ç, –∫–æ—Ç–æ—Ä—ã–π —É–¥–æ–≤–ª–µ—Ç–≤–æ—Ä—è–µ—Ç –≤—Å–µ–º —É—Å–ª–æ–≤–∏—è–º –ø–æ–∏—Å–∫–∞ (**AND**):
        ```
        [
          // –ò—â–µ–º —Å–ª—É—á–∞–π, –≥–¥–µ id_—Å–ª—É—á–∞—è=B001 –ò –Ω–æ–º–µ—Ä–æ–º_–∑–∞–∫–∞–∑–∞=345
          { "caseId": "B001", "orderNumber": "345" },

          // –¢–∞–∫–∂–µ –∏—â–µ–º —Å–ª—É—á–∞–π, –≥–¥–µ id_—Å–ª—É—á–∞—è=B002
          { "caseId": "B002" }
        ]
        ```
      operationId: findCases
      responses:
        '200':
          $ref: '#/components/responses/CaseSearchResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '413':
          $ref: '#/components/responses/ErrorResponse'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CaseSearchRequest'
            examples:
              –ü—Ä–∏–º–µ—Ä –ø–æ–∏—Å–∫–∞ —á–µ—Ç—ã—Ä—ë—Ö —Å–ª—É—á–∞–µ–≤ (2 —Å–ª—É—á–∞—è –∏—â—É—Ç—Å—è –ø–æ caseNumber, 1 —Å–ª—É—á–∞–π –ø–æ orderNumber, 1 —Å–ª—É—á–∞–π –ø–æ bioMaterialId):
                value:
                  - caseNumber: B00000001
                  - orderNumber: '000000171'
                  - bioMaterialId: '1021031041'
                  - caseNumber: B00000002
              –ü—Ä–∏–º–µ—Ä –ø–æ–∏—Å–∫–∞ –¥–≤—É—Ö —Å–ª—É—á–∞–µ–≤ (–ø–µ—Ä–≤—ã–π —Å–ª—É—á–∞–π –∏—â–µ—Ç—Å—è –ø–æ —Å–æ–æ—Ç–≤–µ—Ç—Å—Ç–≤–∏—é caseNumber –ò orderNumber, –≤—Ç–æ—Ä–æ–π - —Ç–æ–ª—å–∫–æ –ø–æ —Å–æ–æ—Ç–≤–µ—Ç—Å—Ç–≤–∏—é caseNumber):
                value:
                  - caseNumber: B00000001
                    orderNumber: '000000171'
                  - bioMaterialId: '1021031041'
    parameters: []
  /case/mmc:
    post:
      summary: –ò–º–ø–æ—Ä—Ç —Å–ø–∏—Å–∫–∞ –∏–º–ø–æ—Ä—Ç–∏—Ä–æ–≤–∞–Ω–Ω—ã—Ö –ú–ú–ö –≤ LIS
      operationId: upsertMmc
      responses:
        '200':
          $ref: '#/components/responses/BulkMethodResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '413':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          description: Internal Server Error
      description: –õ–ò–° –¥–æ–ª–∂–µ–Ω –ø—Ä–∏–Ω–∏–º–∞—Ç—å –æ—Ç OneCell –Ω–∞–±–æ—Ä –ú–ú–ö (–º–µ–¥–∏–Ω–∏—Å–∫–æ–≥–æ –º–µ–¥–∏–∞ –∫–æ–Ω—Ç–µ–Ω—Ç–∞ - –º–∏–∫—Ä–æ, –º–∞–∫—Ä–æ —Å–ª–∞–π–¥–æ–≤ –∏ –¥–æ–∫—É–º–µ–Ω—Ç–æ–≤) –∏ —Å–æ—Ö—Ä–∞–Ω—è—Ç—å –≤ —Å–≤–æ–µ–π –±–∞–∑–µ –¥–∞–Ω–Ω—ã—Ö –¥–ª—è –ø–æ—Å–ª–µ–¥—É—é—â–µ–≥–æ –≤—ã–≤–æ–¥–∞ –≤—Ä–∞—á—É –ø—Ä—è–º—ã—Ö —Å—Å—ã–ª–æ–∫ –Ω–∞ —Å–ª–∞–π–¥—ã –∏ –¥–æ–∫—É–º–µ–Ω—Ç—ã –≤ –∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å–µ OneCell.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UpsertLisCaseMmcDto'
    parameters: []
  /case/{caseNumber}/medical-report:
    parameters:
      - schema:
          type: string
        name: caseNumber
        in: path
        required: true
        description: –£–Ω–∏–∫–∞–ª—å–Ω—ã–π –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä –º–µ–¥. —Å–ª—É—á–∞—è
    post:
      summary: –ò–º–ø–æ—Ä—Ç –º–µ–¥. –∑–∞–∫–ª—é—á–µ–Ω–∏—è –≤ LIS
      operationId: upsertCaseMedicalReport
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationStatusDto'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '413':
          $ref: '#/components/responses/ErrorResponse'
      description: –°–æ–∑–¥–∞–Ω–∏–µ/–æ–±–Ω–æ–≤–ª–µ–Ω–∏–µ –º–µ–¥–∏—Ü–∏–Ω—Å–∫–æ–≥–æ –∑–∞–∫–ª—é—á–µ–Ω–∏—è –≤ PACS OneCell
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpsertPacsMedicalReportDto'
        description: ''
  /research-request:
    post:
      summary: üÜï –í—ã–≥—Ä—É–∑–∫–∞ –º–∞—Å—Å–∏–≤–∞ –ó–∞–ø—Ä–æ—Å–æ–≤ –Ω–∞ –î–æ–∑–∞–∫–∞–∑ (–ó–Ω–î)
      operationId: sendResearchRequests
      description: |-
        –ü–æ –¥–∞–Ω–Ω–æ–º—É —ç–Ω–¥–ø–æ–∏–Ω—Ç—É –ü–ê–ö–° OneCell –±—É–¥–µ—Ç –≤—ã–≥—Ä—É–∂–∞—Ç—å –≤ –õ–ò–° –º–∞—Å—Å–∏–≤ –ó–∞–ø—Ä–æ—Å–æ–≤ –Ω–∞ –î–æ–∑–∞–∫–∞–∑.

        –õ–ò–° –æ–±—è–∑–∞–Ω –æ—Ç–≤–µ—Ç–∏—Ç—å –Ω–∞ –∫–∞–∂–¥—ã–π –∑–∞–ø—Ä–æ—Å –≤ –º–∞—Å—Å–∏–≤–µ **–∏–Ω–¥–∏–≤–∏–¥—É–∞–ª—å–Ω–æ** –æ–¥–Ω–∏–º –∏–∑ —Å–ª–µ–¥—É—é—â–∏—Ö –æ–±—Ä–∞–∑–æ–≤:
        1. –ï—Å–ª–∏ –ó–Ω–î —Å–æ—Ö—Ä–∞–Ω–µ–Ω–∞ —É—Å–ø–µ—à–Ω–æ, —Ç–æ –õ–ò–° –¥–æ–ª–∂–µ–Ω –æ—Ç–≤–µ—Ç–∏—Ç—å —Å–ª–µ–¥—É—é—â–∏–º –æ–±—Ä–∞–∑–æ–º, –∞ —Ç–∞–∫–∂–µ **—Å–æ–∑–¥–∞—Ç—å –∏ –≤—ã–≥—Ä—É–∑–∏—Ç—å –æ—Ç–¥–µ–ª—å–Ω—ã–º –∑–∞–ø—Ä–æ—Å–æ–º –í–°–ï —Å—Ç—ë–∫–ª–∞**, —É–∫–∞–∑–∞–Ω–Ω—ã–µ –≤ –ó–Ω–î:
            ```json
              {
                "success": true,
                "retryable": false
              }
            ```
        2. –ï—Å–ª–∏ –ó–Ω–î –Ω–µ —Å–æ—Ö—Ä–∞–Ω–µ–Ω–∞ –∏–∑-–∑–∞ –≤—Ä–µ–º–µ–Ω–Ω–æ–π –æ—à–∏–±–∫–∏ (–Ω–∞–ø—Ä. –≤–Ω–µ—à–Ω–∏–π —Å–µ—Ä–≤–µ—Ä –Ω–µ–¥–æ—Å—Ç—É–ø–µ–Ω), —Ç–æ –õ–ò–° –¥–æ–ª–∂–µ–Ω –æ—Ç–≤–µ—Ç–∏—Ç—å —Å–ª–µ–¥—É—é—â–∏–º –æ–±—Ä–∞–∑–æ–º:
            ```json
              {
                "success": false,
                "retryable": true, // <-- TRUE –≥–æ–≤–æ—Ä–∏—Ç –æ —Ç–æ–º, —á—Ç–æ OneCell –î–û–õ–ñ–ï–ù –ø–æ–≤—Ç–æ—Ä–∏—Ç—å –ø–æ–ø—ã—Ç–∫—É –≤—ã–≥—Ä—É–∑–∫–∏ —ç—Ç–æ–≥–æ –æ–±—ä–µ–∫—Ç–∞ —á–µ—Ä–µ–∑ 5 –º–∏–Ω—É—Ç
                error: { ... –∑–¥–µ—Å—å –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è –æ–± –æ—à–∏–±–∫–µ (–∫–∞–∫ –≤ –ø—Ä–∏–º–µ—Ä–µ –Ω–∏–∂–µ) ... } 
              }
            ```
        3. –ï—Å–ª–∏ –ó–Ω–î –Ω–µ —Å–æ—Ö—Ä–∞–Ω–µ–Ω–∞ –∏–∑-–∑–∞ –Ω–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω–æ–≥–æ –∑–∞–ø—Ä–æ—Å–∞ —Å–æ —Å—Ç–æ—Ä–æ–Ω—ã OneCell (–Ω–∞–ø—Ä. —É–∫–∞–∑–∞–Ω–Ω–æ–µ —Å—Ç–µ–∫–ª–æ –æ—Ç—Å—É—Ç—Å—Ç–≤—É–µ—Ç –≤ –õ–ò–°), —Ç–æ –õ–ò–° –¥–æ–ª–∂–µ–Ω –æ—Ç–≤–µ—Ç–∏—Ç—å —Å–ª–µ–¥—É—é—â–∏–º –æ–±—Ä–∞–∑–æ–º: 
            ```json
              {
                "success": false,
                "retryable": false, // <-- FALSE –≥–æ–≤–æ—Ä–∏—Ç –æ —Ç–æ–º, —á—Ç–æ OneCell –ù–ï –î–û–õ–ñ–ï–ù –¥–µ–ª–∞—Ç—å –ø–æ–≤—Ç–æ—Ä–Ω—ã—Ö –ø–æ–ø—ã—Ç–æ–∫ –≤—ã–≥—Ä—É–∑–∫–∏ —ç—Ç–æ–≥–æ –æ–±—ä–µ–∫—Ç–∞, –∞ –≤–º–µ—Å—Ç–æ —ç—Ç–æ–≥–æ –ø–µ—Ä–µ–≤–µ—Å—Ç–∏ –ó–Ω–î –≤ —Å—Ç–∞—Ç—É—Å "–û—à–∏–±–∫–∞"
                error: { ... –∑–¥–µ—Å—å –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è –æ–± –æ—à–∏–±–∫–µ (–∫–∞–∫ –≤ –ø—Ä–∏–º–µ—Ä–µ –Ω–∏–∂–µ) ... } 
              }
            ```
      responses:
        '200':
          $ref: '#/components/responses/BulkMethodResponseWithRetry'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '413':
          $ref: '#/components/responses/ErrorResponse'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ResearchRequest'
    parameters: []
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    CaseSearchRequest:
      type: object
      examples:
        - caseNumber: B00000001
        - orderNumber: '000000171'
        - bioMaterialId: '1021031041'
      description: –ó–∞–ø—Ä–æ—Å –¥–ª—è –ø–æ–∏—Å–∫–∞ –º–µ–¥–∏—Ü–∏–Ω—Å–∫–æ–≥–æ —Å–ª—É—á–∞—è. –í—Å–µ–≥–¥–∞ –¥–æ–ª–∂–Ω–æ –±—ã—Ç—å —É–∫–∞–∑–∞–Ω–æ —Ä–æ–≤–Ω–æ –æ–¥–Ω–æ –ø–æ–ª–µ (`caseNumber`, `orderNumber`, –ª–∏–±–æ `bioMaterialId`). –ï—Å–ª–∏ –≤—Å–µ –ø–æ–ª—è –æ–¥–Ω–æ–≤—Ä–µ–º–µ–Ω–Ω–æ –∏–º–µ—é—Ç –ø—É—Å—Ç—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è, –ª–∏–±–æ –≤—Å–µ –ø–æ–ª—è –∏–º–µ—é—Ç –æ–¥–Ω–æ–≤—Ä–µ–º–µ–Ω–Ω–æ –∏–º–µ—é—Ç –Ω–µ–ø—É—Å—Ç—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è - –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –≤—ã–¥–∞—Ç—å –æ—à–∏–±–∫—É `400 Bad Request`
      title: CaseSearchRequest
      properties:
        caseNumber:
          type: string
          description: –£–Ω–∏–∫–∞–ª—å–Ω—ã–π –Ω–æ–º–µ—Ä —Å–ª—É—á–∞—è
          example: 5130-I22006394
        orderNumber:
          type: string
          description: –£–Ω–∏–∫–∞–ª—å–Ω—ã–π –Ω–æ–º–µ—Ä –∑–∞–∫–∞–∑–∞
          example: ORD-000000001
        bioMaterialId:
          type: string
          description: –£–Ω–∏–∫–∞–ª—å–Ω—ã–π –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä –±–∏–æ–º–∞—Ç–µ—Ä–∏–∞–ª–∞ –≤ —Ä–∞–º–∫–∞—Ö —Å–ª—É—á–∞—è. –ù–∞–ø—Ä–∏–º–µ—Ä, ID –ø—Ä–æ–±—ã (–∫–æ–Ω—Ç–µ–π–Ω–µ—Ä–∞)
          example: 5130-I22006394-0001
    ParentCaseRef:
      title: ParentCaseRef
      type: object
      description: |-
        –°—Å—ã–ª–∫–∞ –Ω–∞ —Ä–æ–¥–∏—Ç–µ–ª—å—Å–∫–∏–π —Å–ª—É—á–∞–π

        üÜï–î–æ–±–∞–≤–ª–µ–Ω–æ –≤ –≤–µ—Ä—Å–∏–∏ API 1.10
      required:
        - caseNumber
      properties:
        caseNumber:
          type: string
          description: –£–Ω–∏–∫–∞–ª—å–Ω—ã–π –Ω–æ–º–µ—Ä —Å–ª—É—á–∞—è –≤ –õ–ò–° –õ–∞–±—Ñ–æ—Ä—Å, —è–≤–ª—è—é—â–∏–π—Å—è —Ä–æ–¥–∏—Ç–µ–ª–µ–º.
          pattern: ^(?!\s*$).+
          example: 5130-I11004661
        workspaceId:
          type: number
          format: int64
          description: |-
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä Workspace, –≤ –∫–æ—Ç–æ—Ä–æ–º –Ω–∞—Ö–æ–¥–∏—Ç—Å—è —Ä–æ–¥–∏—Ç–µ–ª—å—Å–∫–∏–π —Å–ª—É—á–∞–π.

            –ù–µ–æ–±—Ö–æ–¥–∏–º–æ –∑–∞–ø–æ–ª–Ω—è—Ç—å —Ç–æ–ª—å–∫–æ –µ—Å–ª–∏ —Ä–æ–¥–∏—Ç–µ–ª—å—Å–∫–∏–π —Å–ª—É—á–∞–π –Ω–∞—Ö–æ–¥–∏—Ç—Å—è –≤ –¥—Ä—É–≥–æ–π –ª–∞–±–æ—Ä–∞—Ç–æ—Ä–∏–∏.

            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä—ã Workspace —Ñ–∏–∫—Å–∏—Ä–æ–≤–∞–Ω—ã –¥–ª—è –∫–∞–∂–¥–æ–π –ª–∞–±–æ—Ä–∞—Ç–æ—Ä–∏–∏ –ø—Ä–µ–¥–æ—Å—Ç–∞–≤–ª—è—é—Ç—Å—è OneCell –≤–æ –≤—Ä–µ–º—è –Ω–∞—Å—Ç—Ä–æ–π–∫–∏ –∏–Ω—Ç–µ–≥—Ä–∞—Ü–∏–∏.
          pattern: ^(?!\s*$).+
          example: 45
    PatientDto:
      title: PatientDto
      type: object
      description: –ò–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è –æ –ø–∞—Ü–∏–µ–Ω—Ç–µ –≤ –õ–ò–° –¥–ª—è –≤—ã–≥—Ä—É–∑–∫–∏ –≤ PACS OneCell
      properties:
        patientId:
          type: string
          description: –£–Ω–∏–∫–∞–ª—å–Ω—ã–π ID –ø–∞—Ü–∏–µ–Ω—Ç–∞ –≤ —Ä–∞–º–∫–∞—Ö –º–µ–¥. —É—á—Ä–µ–∂–¥–µ–Ω–∏—è
          pattern: ^(?!\s*$).+
          example: 1323-000111222
        fullname:
          type: string
          description: –§–ò–û –ø–∞—Ü–∏–µ–Ω—Ç–∞
          pattern: ^(?!\s*$).+
          example: –ò–≤–∞–Ω–æ–≤ –ò–≤–∞–Ω –ò–≤–∞–Ω–æ–≤–∏—á
        birthDate:
          type: string
          description: –î–∞—Ç–∞ —Ä–æ–∂–¥–µ–Ω–∏—è –ø–∞—Ü–∏–µ–Ω—Ç–∞
          format: date
          example: '1985-01-01'
        sex:
          type: string
          description: –ü–æ–ª –ø–∞—Ü–∏–µ–Ω—Ç–∞
          enum:
            - MALE
            - FEMALE
          example: MALE
        globalPatientId:
          type: string
          description: –ì–ª–æ–±–∞–ª—å–Ω–æ —É–Ω–∏–∫–∞–ª—å–Ω—ã–π ID –ø–∞—Ü–∏–µ–Ω—Ç–∞ –≤ —Ä–∞–º–∫–∞—Ö —Å—Ç—Ä–∞–Ω—ã (–Ω–∞–ø—Ä. –ï–ú–ò–ê–° –∏–ª–∏ –°–ù–ò–õ–°). –î–∞–Ω–Ω—ã–π –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä –∏—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è –¥–ª—è –æ–±—ä–µ–¥–∏–Ω–µ–Ω–∏—è –ø–∞—Ü–∏–µ–Ω—Ç–æ–≤ –∏–∑ –Ω–µ—Å–∫–æ–ª—å–∫–∏—Ö –º–µ–¥–∏—Ü–∏–Ω—Å–∫–∏—Ö —É—á—Ä–µ–∂–¥–µ–Ω–∏–π
          example: '1900121345'
      required:
        - patientId
        - fullname
        - birthDate
        - sex
    DictionaryRef:
      title: DictionaryRef
      type: object
      description: –°—Å—ã–ª–∫–∞ –Ω–∞ –∑–Ω–∞—á–µ–Ω–∏–µ –≤ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–µ
      required:
        - id
        - name
      properties:
        id:
          type: string
          description: |
            **–£–Ω–∏–∫–∞–ª—å–Ω—ã–π** –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä –∑–∞–ø–∏—Å–∏ –≤ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–µ. –ò—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è –¥–ª—è –ø–æ–∏—Å–∫–∞ –∑–∞–ø–∏—Å–∏ –ø—Ä–∏ –∞–≤—Ç–æ–æ–±–Ω–æ–≤–ª–µ–Ω–∏–∏ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–æ–≤.
            **–û—Ç–≤–µ—Å—Ç–≤–µ–Ω–Ω–æ –æ—Ç–Ω–æ—Å–∏—Ç–µ—Å—å –∫ –≤—ã–±–æ—Ä—É –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–∞ –¥–ª—è —ç—Ç–æ–≥–æ –ø–æ–ª—è.**
            –ê–≤—Ç–æ–æ–±–Ω–æ–≤–ª–µ–Ω–∏–µ —Ä–∞–±–æ—Ç–∞–µ—Ç —Å–ª–µ–¥—É—é—â–∏–º –æ–±—Ä–∞–∑–æ–º:
            1. –ù–∞–ø—Ä. –í—ã –æ–ø—É–±–ª–∏–∫–æ–≤–∞–ª–∏ –º–µ–¥–∏—Ü–∏–Ω—Å–∫–∏–π —Å–ª—É—á–∞–π —Å Icd10 = `(id=123, shortName=C40.0, name=ABCDEF)`
            2. –ó–∞—Ç–µ–º –í—ã –æ–ø—É–±–ª–∏–∫–æ–≤–∞–ª–∏ –¥—Ä—É–≥–æ–π –º–µ–¥–∏—Ü–∏–Ω—Å–∫–∏–π —Å–ª—É—á–∞–π —Å Icd10 = `(id=123, shortName=C41.0, name=DEADBEEF)`
            3. –î–ª—è –ø–µ—Ä–≤–æ–≥–æ –º–µ–¥–∏—Ü–∏–Ω—Å–∫–æ–≥–æ —Å–ª—É—á–∞—è –∑–Ω–∞—á–µ–Ω–∏–µ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–∞ —Ç–æ–∂–µ –ø–µ—Ä–µ–∏–º–µ–Ω—É–µ—Ç—Å—è –∏–∑ `C40.0 ABCDEF` –≤ `C41.0 DEADBEEF`, –ø–æ—Å–∫–æ–ª—å–∫—É –¥–ª—è —ç—Ç–æ–≥–æ —Å–ª—É—á–∞—è –±—ã–ª–æ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–æ —Ç–æ –∂–µ —Å–∞–º–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ `id`  –≤ –≤—ã–±—Ä–∞–Ω–Ω–æ–º —ç–ª–µ–º–µ–Ω—Ç–µ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–∞.
          pattern: ^(?!\s*$).+
          example: '123'
        shortName:
          type: string
          description: |-
            **NEW!**
            –ö–æ—Ä–æ—Ç–∫–æ–µ –Ω–∞–∑–≤–∞–Ω–∏–µ –∑–∞–ø–∏—Å–∏ –≤ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–µ, –æ—Ç–æ–±—Ä–∞–∂–∞–µ–º–æ–µ –≤ –∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å–µ (–∫–æ–¥ —ç–ª–µ–º–µ–Ω—Ç–∞ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–∞). –ù–∞–ø—Ä–∏–º–µ—Ä, "HE".

            –ï—Å–ª–∏ –ø–æ–ª–µ `shortName` –Ω–µ –∑–∞–ø–æ–ª–Ω–µ–Ω–æ –∏–ª–∏ –Ω–µ —É–∫–∞–∑–∞–Ω–æ –≤ –∑–∞–ø—Ä–æ—Å–µ - OneCell –Ω–∞ —Å–≤–æ–µ–π —Å—Ç–æ—Ä–æ–Ω–µ –±—É–¥–µ—Ç –±—Ä–∞—Ç—å –∑–Ω–∞—á–µ–Ω–∏–µ –∏–∑ –ø–æ–ª—è `id` –¥–ª—è –æ—Ç–æ–±—Ä–∞–∂–µ–Ω–∏—è –≤ –∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å–µ.
          pattern: ^(?!\s*$).+
          example: –ö—Ä—Ç–∫–ù–∑–≤
        name:
          type: string
          description: –ü–æ–ª–Ω–æ–µ –Ω–∞–∑–≤–∞–Ω–∏–µ –∑–∞–ø–∏—Å–∏ –≤ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–µ, –æ—Ç–æ–±—Ä–∞–∂–∞–µ–º–æ–µ –≤ –∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å–µ. –ù–∞–ø—Ä–∏–º–µ—Ä, "–ì–µ–º–∞—Ç–æ–∫—Å–∏–ª–∏–Ω".
          pattern: ^(?!\s*$).+
          example: –ü–æ–ª–Ω–æ–µ –Ω–∞–∑–≤–∞–Ω–∏–µ —ç–ª–µ–º–µ–Ω—Ç–∞ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–∞
    UserRef:
      title: UserRef
      type: object
      description: –°—Å—ã–ª–∫–∞ –Ω–∞ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è –≤ Active Directory
      properties:
        userIdentifier:
          type: string
          description: –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è –≤ AD (sAMAccountName)
          pattern: ^(?!\s*$).+
        fullname:
          type: string
          description: –ü–æ–ª–Ω–æ–µ –∏–º—è –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è
          pattern: ^(?!\s*$).+
      required:
        - userIdentifier
        - fullname
    NoteDto:
      title: NoteDto
      type: object
      description: |-
        –ò–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è –æ –∑–∞–º–µ—Ç–∫–µ –≤ –º–µ–¥. —Å–ª—É—á–∞–µ –Ω–∞ —Å—Ç–æ—Ä–æ–Ω–µ –õ–ò–° –¥–ª—è –≤—ã–≥—Ä—É–∑–∫–∏ –≤ PACS OneCell
        –û–±—Ä–∞—Ç–∏—Ç–µ –≤–Ω–∏–º–∞–Ω–∏–µ, —á—Ç–æ –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –æ–±—è–∑–∞—Ç–µ–ª—å–Ω–æ —É–∫–∞–∑–∞—Ç—å –∞–≤—Ç–æ—Ä–∞ –∑–∞–º–µ—Ç–∫–∏ —á–µ—Ä–µ–∑ –ø–æ–ª–µ 
        `author`, –ª–∏–±–æ —á–µ—Ä–µ–∑ –ø–æ–ª–µ `authorExternalName`
      properties:
        noteId:
          type: string
          description: –£–Ω–∏–∫–∞–ª—å–Ω—ã–π –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä –∑–∞–º–µ—Ç–∫–∏ –≤ —Ä–∞–º–∫–∞—Ö –º–µ–¥. —Å–ª—É—á–∞—è
          pattern: ^(?!\s*$).+
          example: NOTE00001
        author:
          $ref: '#/components/schemas/UserRef'
          description: –ê–≤—Ç–æ—Ä –∑–∞–º–µ—Ç–∫–∏ (–µ—Å–ª–∏ –µ—Å—Ç—å –∞–∫–∫–∞—É–Ω—Ç –≤ Active Directory)
        authorExternalName:
          type: string
          description: –ò–º—è –∞–≤—Ç–æ—Ä–∞ –∑–∞–º–µ—Ç–∫–∏ (—Ç–æ–ª—å–∫–æ –µ—Å–ª–∏ –Ω–µ—Ç –∞–∫–∫–∞—É–Ω—Ç–∞ –≤ Active Directory)
          pattern: ^(?!\s*$).+
          example: –í–∞—Å–∏–ª–∏–π –ü–µ—Ç—Ä–æ–≤–∏—á
        createdAt:
          type: string
          format: date-time
          description: –î–∞—Ç–∞ –∏ –≤—Ä–µ–º—è —Å–æ–∑–¥–∞–Ω–∏—è –∑–∞–º–µ—Ç–∫–∏
          example: '2024-09-17T13:38:27+00:00'
        body:
          type: string
          description: –°–æ–¥–µ—Ä–∂–∏–º–æ–µ –∑–∞–º–µ—Ç–∫–∏
          pattern: ^(?!\s*$).+
          example: –°–ª—É—á–∞–π –±—ã–ª –ø–µ—Ä–µ–º–µ—â—ë–Ω –∏–∑ –∞—Ä—Ö–∏–≤–∞ –í–∞—Å–∏–ª–∏–µ–º –ü–µ—Ç—Ä–æ–≤–∏—á–µ–º
      required:
        - noteId
        - createdAt
        - body
    BioMaterialInfoDto:
      title: BioMaterialInfoDto
      type: object
      description: –ë–∏–æ–º–∞—Ç–µ—Ä–∏–∞–ª
      properties:
        bioMaterialId:
          type: string
          description: –£–Ω–∏–∫–∞–ª—å–Ω—ã–π –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä –±–∏–æ–º–∞—Ç–µ—Ä–∏–∞–ª–∞ –≤ —Ä–∞–º–∫–∞—Ö —Å–ª—É—á–∞—è. –ù–∞–ø—Ä–∏–º–µ—Ä, ID –ø—Ä–æ–±—ã (–∫–æ–Ω—Ç–µ–π–Ω–µ—Ä–∞)
          pattern: ^(?!\s*$).+
          example: 5130-I22006394-0001
        bioMaterial:
          type: string
          description: –ë–∏–æ–º–∞—Ç–µ—Ä–∏–∞–ª
          pattern: ^(?!\s*$).+
          example: –ö–æ—Å—Ç–Ω–∞—è —Ç–∫–∞–Ω—å
        site:
          $ref: '#/components/schemas/DictionaryRef'
        processNature:
          $ref: '#/components/schemas/DictionaryRef'
        fragmentsCount:
          type: integer
          format: int64
          description: –ö–æ–ª–∏—á–µ—Å—Ç–≤–æ —Ñ—Ä–∞–≥–º–µ–Ω—Ç–æ–≤
          minimum: 0
          example: 3
        blocksCount:
          type: integer
          format: int64
          description: –ö–æ–ª–∏—á–µ—Å—Ç–≤–æ –±–ª–æ–∫–æ–≤
          minimum: 0
          example: 4
        slidesCount:
          type: integer
          format: int64
          description: –ö–æ–ª–∏—á–µ—Å—Ç–≤–æ —Å–ª–∞–π–¥–æ–≤
          minimum: 0
          example: 5
      required:
        - bioMaterialId
    BlockInfoDto:
      title: BlockInfoDto
      type: object
      description: –ë–ª–æ–∫
      properties:
        blockId:
          type: string
          description: –£–Ω–∏–∫–∞–ª—å–Ω—ã–π –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä –±–ª–æ–∫–∞ –≤ —Ä–∞–º–∫–∞—Ö —Å–ª—É—á–∞—è. –ù–∞–ø—Ä–∏–º–µ—Ä, –Ω–æ–º–µ—Ä/—à—Ç—Ä–∏—Ö–∫–æ–¥ –±–ª–æ–∫–∞
          pattern: ^(?!\s*$).+
          example: 1-2
        site:
          $ref: '#/components/schemas/DictionaryRef'
      required:
        - blockId
    StainDictionaryRef:
      title: StainDictionaryRef
      type: object
      description: –°—Å—ã–ª–∫–∞ –Ω–∞ –∑–Ω–∞—á–µ–Ω–∏–µ –≤ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–µ "–û–∫—Ä–∞—Å–∫–∏"
      required:
        - id
        - name
      properties:
        id:
          type: string
          description: |
            **–£–Ω–∏–∫–∞–ª—å–Ω—ã–π** –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä –∑–∞–ø–∏—Å–∏ –≤ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–µ. –ò—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è –¥–ª—è –ø–æ–∏—Å–∫–∞ –∑–∞–ø–∏—Å–∏ –ø—Ä–∏ –∞–≤—Ç–æ–æ–±–Ω–æ–≤–ª–µ–Ω–∏–∏ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–æ–≤.
            **–û—Ç–≤–µ—Å—Ç–≤–µ–Ω–Ω–æ –æ—Ç–Ω–æ—Å–∏—Ç–µ—Å—å –∫ –≤—ã–±–æ—Ä—É –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–∞ –¥–ª—è —ç—Ç–æ–≥–æ –ø–æ–ª—è.**
            –ê–≤—Ç–æ–æ–±–Ω–æ–≤–ª–µ–Ω–∏–µ —Ä–∞–±–æ—Ç–∞–µ—Ç —Å–ª–µ–¥—É—é—â–∏–º –æ–±—Ä–∞–∑–æ–º:
            1. –ù–∞–ø—Ä. –í—ã –æ–ø—É–±–ª–∏–∫–æ–≤–∞–ª–∏ –º–µ–¥–∏—Ü–∏–Ω—Å–∫–∏–π —Å–ª—É—á–∞–π —Å Stain = `(id=123, shortName=H&E, name=–ì–µ–º–∞—Ç–æ–∫—Å–∏–ª–∏–Ω)`
            2. –ó–∞—Ç–µ–º –í—ã –æ–ø—É–±–ª–∏–∫–æ–≤–∞–ª–∏ –¥—Ä—É–≥–æ–π –º–µ–¥–∏—Ü–∏–Ω—Å–∫–∏–π —Å–ª—É—á–∞–π —Å Stain = `(id=123, shortName=Ki67, name=Ki-67)`
            3. –î–ª—è –ø–µ—Ä–≤–æ–≥–æ –º–µ–¥–∏—Ü–∏–Ω—Å–∫–æ–≥–æ —Å–ª—É—á–∞—è –∑–Ω–∞—á–µ–Ω–∏–µ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–∞ —Ç–æ–∂–µ –ø–µ—Ä–µ–∏–º–µ–Ω—É–µ—Ç—Å—è –∏–∑ `H&E –ì–µ–º–∞—Ç–æ–∫—Å–∏–ª–∏–Ω` –≤ `Ki67 Ki-67`, –ø–æ—Å–∫–æ–ª—å–∫—É –¥–ª—è —ç—Ç–æ–≥–æ —Å–ª—É—á–∞—è –±—ã–ª–æ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–æ —Ç–æ –∂–µ —Å–∞–º–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ `id`  –≤ –≤—ã–±—Ä–∞–Ω–Ω–æ–º —ç–ª–µ–º–µ–Ω—Ç–µ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–∞.
          pattern: ^(?!\s*$).+
          example: '00001'
        shortName:
          type: string
          description: |-
            **NEW!**
            –ö–æ—Ä–æ—Ç–∫–æ–µ –Ω–∞–∑–≤–∞–Ω–∏–µ –∑–∞–ø–∏—Å–∏ –≤ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–µ, –æ—Ç–æ–±—Ä–∞–∂–∞–µ–º–æ–µ –≤ –∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å–µ (–∫–æ–¥ —ç–ª–µ–º–µ–Ω—Ç–∞ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–∞). –ù–∞–ø—Ä–∏–º–µ—Ä, "HE".

            –ï—Å–ª–∏ –ø–æ–ª–µ `shortName` –Ω–µ –∑–∞–ø–æ–ª–Ω–µ–Ω–æ –∏–ª–∏ –Ω–µ —É–∫–∞–∑–∞–Ω–æ –≤ –∑–∞–ø—Ä–æ—Å–µ - OneCell –Ω–∞ —Å–≤–æ–µ–π —Å—Ç–æ—Ä–æ–Ω–µ –±—É–¥–µ—Ç –±—Ä–∞—Ç—å –∑–Ω–∞—á–µ–Ω–∏–µ –∏–∑ –ø–æ–ª—è `id` –¥–ª—è –æ—Ç–æ–±—Ä–∞–∂–µ–Ω–∏—è –≤ –∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å–µ.
          pattern: ^(?!\s*$).+
          example: H&E
        name:
          type: string
          description: –ü–æ–ª–Ω–æ–µ –Ω–∞–∑–≤–∞–Ω–∏–µ –∑–∞–ø–∏—Å–∏ –≤ —Å–ø—Ä–∞–≤–æ—á–Ω–∏–∫–µ, –æ—Ç–æ–±—Ä–∞–∂–∞–µ–º–æ–µ –≤ –∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å–µ. –ù–∞–ø—Ä–∏–º–µ—Ä, "–ì–µ–º–∞—Ç–æ–∫—Å–∏–ª–∏–Ω –≠–æ–∑–∏–Ω".
          pattern: ^(?!\s*$).+
          example: –ì–µ–º–∞—Ç–æ–∫—Å–∏–ª–∏–Ω –≠–æ–∑–∏–Ω
        stainType:
          type: string
          description: |-
            üÜï–î–æ–±–∞–≤–ª–µ–Ω–æ –≤ –≤–µ—Ä—Å–∏–∏ API 1.10

            –¢–∏–ø –æ–∫—Ä–∞—Å–∫–∏. HC - –≥–∏—Å—Ç–æ—Ö–∏–º–∏—á–µ—Å–∫–∞—è, IHC - –∏–º–º—É–Ω–æ–≥–∏—Å—Ç–æ—Ö–∏–º–∏—á–µ—Å–∫–∞—è.
          enum:
            - HC
            - IHC
          example: HC
        availableForOrder:
          type: boolean
          description: |-
            üÜï–î–æ–±–∞–≤–ª–µ–Ω–æ –≤ –≤–µ—Ä—Å–∏–∏ API 1.10

            –î–æ—Å—Ç—É–ø–Ω–∞ –ª–∏ –æ–∫—Ä–∞—Å–∫–∞ –¥–ª—è –∑–∞–ø—Ä–æ—Å–æ–≤ –Ω–∞ –¥–æ–∑–∞–∫–∞–∑.
          example: false
    SlideInfoDto:
      title: SlideInfoDto
      type: object
      description: –°—Ç–µ–∫–ª–æ
      properties:
        slideId:
          type: string
          description: –£–Ω–∏–∫–∞–ª—å–Ω—ã–π –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å—Ç–µ–∫–ª–∞ –≤ —Ä–∞–º–∫–∞—Ö —Å–ª—É—á–∞—è. –ù–∞–ø—Ä–∏–º–µ—Ä, –Ω–æ–º–µ—Ä/—à—Ç—Ä–∏—Ö–∫–æ–¥ —Å—Ç–µ–∫–ª–∞
          pattern: ^(?!\s*$).+
          example: 5130-I22006394-1-2-3
        blockId:
          type: string
          description: –£–Ω–∏–∫–∞–ª—å–Ω—ã–π –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä –±–ª–æ–∫–∞ –≤ —Ä–∞–º–∫–∞—Ö —Å–ª—É—á–∞—è. –ù–∞–ø—Ä–∏–º–µ—Ä, –Ω–æ–º–µ—Ä/—à—Ç—Ä–∏—Ö–∫–æ–¥ –±–ª–æ–∫–∞
          pattern: ^(?!\s*$).+
          example: 1-2
        stain:
          $ref: '#/components/schemas/StainDictionaryRef'
        researchRequestSlideId:
          type: string
          description: |-
            üÜï–î–æ–±–∞–≤–ª–µ–Ω–æ –≤ –≤–µ—Ä—Å–∏–∏ API 1.10

            ID –∫–æ–Ω–∫—Ä–µ—Ç–Ω–æ–≥–æ —Å—Ç–µ–∫–ª–∞ –∏–∑ –ó–Ω–î. –ù–µ–æ–±—Ö–æ–¥–∏–º–æ, —á—Ç–æ–±—ã OneCell –ø–æ–Ω–∏–º–∞–ª, –∫–∞–∫–æ–µ —Å—Ç–µ–∫–ª–æ –∏–∑ –ó–Ω–î –≥–æ—Ç–æ–≤–æ, –∞ –∫–∞–∫–æ–µ –Ω–µ—Ç.
            –ò–∑–Ω–∞—á–∞–ª—å–Ω–æ –õ–ò–° –¥–æ–ª–∂–µ–Ω –ø–æ–ª—É—á–∞—Ç—å —ç—Ç–æ—Ç ID –æ—Ç OneCell –≤–æ –≤—Ä–µ–º—è –ø–æ–ª—É—á–µ–Ω–∏—è –î–æ–∑–∞–∫–∞–∑–∞, –∞ –∑–∞—Ç–µ–º –ø–µ—Ä–µ–¥–∞–≤–∞—Ç—å –∑–Ω–∞—á–µ–Ω–∏–µ (–∏–∑ –ø–æ–ª—è `slides.*.researchRequestSlideId`) –æ–±—Ä–∞—Ç–Ω–æ –≤ OneCell.

            **–ù–µ –ø—É—Ç–∞–π—Ç–µ** —Å –ø–æ–ª–µ–º `researchRequestId`. –°—é–¥–∞ –Ω—É–∂–Ω–æ —É–∫–∞–∑—ã–≤–∞—Ç—å –∏–º–µ–Ω–Ω–æ –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä **"–°—Ç–µ–∫–ª–∞ –≤ –ó–Ω–î"** (`researchRequestSlideId`), –∞ –Ω–µ —Å–∞–º–æ–π **"–ó–Ω–î"**, —ç—Ç–æ —Ä–∞–∑–Ω—ã–µ –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä—ã.
          example: rrs-bb43d2bc-45b1-4736-a470-cee8e788af61
      required:
        - slideId
    UpsertPacsCaseDto:
      title: UpsertPacsCaseDto
      type: object
      description: –°–æ–∑–¥–∞–Ω–∏–µ/–æ–±–Ω–æ–≤–ª–µ–Ω–∏–µ –º–µ–¥–∏—Ü–∏–Ω—Å–∫–∏—Ö —Å–ª—É—á–∞–µ–≤ –∏ –¥–∞–Ω–Ω—ã—Ö –ø–∞—Ü–∏–µ–Ω—Ç–∞ –≤ PACS OneCell
      properties:
        caseNumber:
          type: string
          description: –£–Ω–∏–∫–∞–ª—å–Ω–æ–µ –Ω–∞–∑–≤–∞–Ω–∏–µ (ID) –º–µ–¥. —Å–ª—É—á–∞—è –≤ –õ–ò–°
          pattern: ^(?!\s*$).+
          example: 5130-I22006394
        parentCases:
          type: array
          description: |-
            üÜï–î–æ–±–∞–≤–ª–µ–Ω–æ –≤ –≤–µ—Ä—Å–∏–∏ API 1.10

            –ú–∞—Å—Å–∏–≤ —Å–æ–¥–µ—Ä–∂–∏—Ç –Ω–æ–º–µ—Ä–∞ —Å–ª—É—á–∞—è –≤ –õ–ò–°, —è–≤–ª—è—é—â–∏—Ö—Å—è —Ä–æ–¥–∏—Ç–µ–ª—è–º–∏. –ú–∞—Å—Å–∏–≤ –º–æ–∂–µ—Ç –±—ã—Ç—å –ø—É—Å—Ç—ã–º, –∞ —Ç–∞–∫–∂–µ –æ—Ç—Å—É—Ç—Å—Ç–≤–æ–≤–∞—Ç—å –≤–æ–≤—Å–µ (–¥–ª—è –æ–±—Ä–∞—Ç–Ω–æ–π —Å–æ–≤–º–µ—Å—Ç–∏–º–æ—Å—Ç–∏).
          items:
            $ref: '#/components/schemas/ParentCaseRef'
        caseDate:
          type: string
          description: –î–∞—Ç–∞ –∑–∞–∫–∞–∑–∞ / –¥–∞—Ç–∞ —Å–æ–∑–¥–∞–Ω–∏—è –º–µ–¥–∏—Ü–∏–Ω—Å–∫–æ–≥–æ —Å–ª—É—á–∞—è
          format: date-time
          example: '2024-09-17T13:38:27+00:00'
        patient:
          $ref: '#/components/schemas/PatientDto'
        services:
          type: array
          items:
            $ref: '#/components/schemas/DictionaryRef'
        incomingIcd10:
          $ref: '#/components/schemas/DictionaryRef'
        orderNumber:
          description: –£–Ω–∏–∫–∞–ª—å–Ω—ã–π –Ω–æ–º–µ—Ä –∑–∞–∫–∞–∑–∞
          type: string
          example: ORD-000000001
        macroDescription:
          type: string
          description: –ú–∞–∫—Ä–æ–æ–ø–∏—Å–∞–Ω–∏–µ
          pattern: ^(?!\s*$).+
          example: –ú–∞–∫—Ä–æ–æ–ø–∏—Å–∞–Ω–∏–µ –º–∞–∫—Ä–æ–æ–ø–∏—Å–∞–Ω–∏–µ –º–∞–∫—Ä–æ–æ–ø–∏—Å–∞–Ω–∏–µ
        description:
          type: string
          description: –ö–ª–∏–Ω–∏—á–µ—Å–∫–∏–µ —Å–≤–µ–¥–µ–Ω–∏—è –∏ –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω–∞—è –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è
          pattern: ^(?!\s*$).+
          example: –ö–ª–∏–Ω–∏—á–µ—Å–∫–æ–µ –æ–ø–∏—Å–∞–Ω–∏–µ...
        doctorId:
          $ref: '#/components/schemas/UserRef'
        materialTakeoutDate:
          type: string
          format: date-time
          description: –î–∞—Ç–∞ –∑–∞–±–æ—Ä–∞ –º–∞—Ç–µ—Ä–∏–∞–ª–∞
          example: '2024-09-17T13:38:27+00:00'
        materialType:
          $ref: '#/components/schemas/DictionaryRef'
        diagnosticProcedureType:
          $ref: '#/components/schemas/DictionaryRef'
        caseResearchType:
          $ref: '#/components/schemas/DictionaryRef'
        comment:
          type: string
          description: –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π –∫ –ø—Ä–æ–±–µ
          pattern: ^(?!\s*$).+
          example: –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π –∫ –ø—Ä–æ–±–µ...
        notes:
          type: array
          items:
            $ref: '#/components/schemas/NoteDto'
        bioMaterials:
          type: array
          items:
            $ref: '#/components/schemas/BioMaterialInfoDto'
        blocks:
          type: array
          items:
            $ref: '#/components/schemas/BlockInfoDto'
        slides:
          type: array
          items:
            $ref: '#/components/schemas/SlideInfoDto'
        department:
          $ref: '#/components/schemas/DictionaryRef'
        task:
          type: string
          description: –ó–∞–¥–∞—á–∞. –ï—Å–ª–∏ –ø–∞—Ç–æ–ª–æ–≥–æ–∞–Ω–∞—Ç–æ–º–∏—á–µ—Å–∫–æ–µ –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏–µ - –∑–∞–¥–∞—á–∞ –ø—Ä–∏–∂–∏–∑–Ω–µ–Ω–Ω–æ–≥–æ –ø–∞—Ç–æ–ª–æ–≥–æ–∞–Ω–∞—Ç–æ–º–∏—á–µ—Å–∫–æ–≥–æ –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏—è
          example: –ü–æ—Å—Ç–∞–Ω–æ–≤–∫–∞ –¥–∏–∞–≥–Ω–æ–∑–∞ –∏ —Å–æ—Å—Ç–∞–≤–ª–µ–Ω–∏–µ —Ä–µ–∫–æ–º–µ–Ω–¥–∞—Ü–∏–π
        researchRequestId:
          type: string
          description: |-
            üÜï–î–æ–±–∞–≤–ª–µ–Ω–æ –≤ –≤–µ—Ä—Å–∏–∏ API 1.10

            –ù–∞ –æ—Å–Ω–æ–≤–∞–Ω–∏–∏ –∫–∞–∫–æ–≥–æ –î–æ–∑–∞–∫–∞–∑–∞ –±—ã–ª —Å–æ–∑–¥–∞–Ω –¥–∞–Ω–Ω—ã–π –°–ª—É—á–∞–π.

            –ò–∑–Ω–∞—á–∞–ª—å–Ω–æ –õ–ò–° –¥–æ–ª–∂–µ–Ω –ø–æ–ª—É—á–∞—Ç—å —ç—Ç–æ—Ç ID –æ—Ç OneCell –≤–æ –≤—Ä–µ–º—è –ø–æ–ª—É—á–µ–Ω–∏—è –ó–Ω–î (–ø–æ–ª–µ `researchRequestId`), –∞ –∑–∞—Ç–µ–º –ø–µ—Ä–µ–¥–∞–≤–∞—Ç—å –∑–Ω–∞—á–µ–Ω–∏–µ –æ–±—Ä–∞—Ç–Ω–æ –≤ OneCell –≤ —ç—Ç–æ–º –ø–æ–ª–µ.
          example: rr-96eafb9e-0b79-493e-b336-3142827db07e
      required:
        - caseNumber
        - caseDate
        - patient
        - services
        - notes
        - bioMaterials
        - blocks
        - slides
    FieldError:
      title: FieldError
      type: object
      properties:
        code:
          type: string
          description: –ö–æ–¥ –æ—à–∏–±–∫–∏ –Ω–∞ –ø–æ–ª–µ
          example: INVALID_SIZE
          pattern: ^(?!\s*$).+
        property:
          type: string
          example: name
          description: –ù–∞–∑–≤–∞–Ω–∏–µ –ø–æ–ª—è
          pattern: ^(?!\s*$).+
        message:
          type: string
          description: –ß–µ–ª–æ–≤–µ–∫–æ-—á–∏—Ç–∞–µ–º–∞—è –æ—à–∏–±–∫–∞ –Ω–∞ –ø–æ–ª–µ
          example: –ü–æ–ª–µ –¥–æ–ª–∂–Ω–æ —Å–æ–¥–µ—Ä–∂–∞—Ç—å –∫–∞–∫ –º–∏–Ω–∏–º—É–º 3 —Å–∏–º–≤–æ–ª–∞
          pattern: ^(?!\s*$).+
        rejectedValue:
          type: string
          example: –í–∞
          description: –û—Ä–∏–≥–∏–Ω–∞–ª—å–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –ø–æ–ª—è
          pattern: ^(?!\s*$).+
        path:
          type: string
          example: patient.fullname
          description: –ü–æ–ª–Ω—ã–π –ø—É—Ç—å –∫ –ø–æ–ª—é
          pattern: ^(?!\s*$).+
      required:
        - code
        - property
        - message
        - path
    ErrorResponseDto:
      title: ErrorResponseDto
      type: object
      properties:
        code:
          type: string
          description: Error code
          example: VALIDATION_FAILED
          pattern: ^(?!\s*$).+
        message:
          type: string
          description: Error message
          example: –ü–æ–ª—è –æ–±—ä–µ–∫—Ç–∞ –∑–∞–ø–æ–ª–Ω–µ–Ω—ã –Ω–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω–æ
          pattern: ^(?!\s*$).+
        fieldErrors:
          type: array
          description: Field errors (on validation error)
          items:
            $ref: '#/components/schemas/FieldError'
      required:
        - code
        - message
    MmcDto:
      title: MmcDto
      type: object
      description: –ò–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è –æ –º–µ–¥–∏—Ü–∏–Ω—Å–∫–æ–º –º–µ–¥–∏–∞-–∫–æ–Ω—Ç–µ–Ω—Ç–µ
      properties:
        contentId:
          type: string
          description: –£–Ω–∏–∫–∞–ª—å–Ω—ã–π –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä –º–µ–¥–∏–∞-–∫–æ–Ω—Ç–µ–Ω—Ç–∞ (–Ω–∞–ø—Ä. –¥–ª—è –º–∏–∫—Ä–æ –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏–π - —à—Ç—Ä–∏—Ö–∫–æ–¥, –¥–ª—è –º–∞–∫—Ä–æ –∏ –¥–æ–∫—É–º–µ–Ω—Ç–æ–≤ - –∏–º—è —Ñ–∞–π–ª–∞)
          example: some-file.pdf
        type:
          type: string
          description: –¢–∏–ø –ú–ú–ö
          enum:
            - DOCUMENT
            - MICRO
            - MACRO
          example: DOCUMENT
        url:
          type: string
          description: –ü—Ä—è–º–æ–π URL –¥–ª—è –æ—Ç–∫—Ä—ã—Ç–∏—è –ú–ú–ö –≤ PACS OneCell –≤ –±—Ä–∞—É–∑–µ—Ä–µ
          format: uri
          example: https://onecell.acme.corp/workspace/12/viewer/123?documentId=431
      required:
        - contentId
        - type
        - url
    UpsertLisCaseMmcDto:
      title: UpsertLisCaseMmcDto
      type: object
      description: –ò–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è –æ –ø—Ä–∏–≤—è–∑–∞–Ω–Ω–æ–º –∫ –º–µ–¥–∏—Ü–∏–Ω—Å–∫–æ–º—É —Å–ª—É—á–∞—é –≤ PACS OneCell –º–µ–¥–∏—Ü–∏–Ω—Å–∫–æ–º –º–µ–¥–∏–∞-–∫–æ–Ω—Ç–µ–Ω—Ç–µ (–ú–ú–ö)
      properties:
        caseNumber:
          type: string
          description: –£–Ω–∏–∫–∞–ª—å–Ω–æ–µ –Ω–∞–∑–≤–∞–Ω–∏–µ (ID) –º–µ–¥. —Å–ª—É—á–∞—è –≤ –õ–ò–°
          example: 5130-I22006394
        mmc:
          type: array
          description: –ü–æ–ª–Ω—ã–π —Å–ø–∏—Å–æ–∫ –ú–ú–ö –¥–∞–Ω–Ω–æ–≥–æ –º–µ–¥–∏—Ü–∏–Ω—Å–∫–æ–≥–æ —Å–ª—É—á–∞—è
          items:
            $ref: '#/components/schemas/MmcDto'
      required:
        - caseNumber
        - mmc
    OperationStatusDto:
      title: OperationStatusDto
      type: object
      properties:
        id:
          type: string
          description: –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å—É—â–Ω–æ—Å—Ç–∏ (ID –º–µ–¥–∏—Ü–∏–Ω—Å–∫–æ–≥–æ —Å–ª—É—á–∞—è/–ø–∞—Ü–∏–µ–Ω—Ç–∞ –∏ —Ç.–ø.)
          pattern: ^(?!\s*$).+
          example: '123123123'
        success:
          type: boolean
          description: –û–ø–µ—Ä–∞—Ü–∏—è –≤—ã–ø–æ–ª–Ω–µ–Ω–∞ —É—Å–ø–µ—à–Ω–æ?
          example: false
        retryable:
          type: boolean
          description: |-
            üÜï–î–æ–±–∞–≤–ª–µ–Ω–æ –≤ –≤–µ—Ä—Å–∏–∏ API 1.10

            –î–æ–ª–∂–Ω–∞ –ª–∏ —Å–∏—Å—Ç–µ–º–∞, –æ—Ç–ø—Ä–∞–≤–∏–≤—à–∞—è –∑–∞–ø—Ä–æ—Å, –ø–æ–≤—Ç–æ—Ä–∏—Ç—å –µ–≥–æ –≤—ã–≥—Ä—É–∑–∫—É –µ—â—ë —Ä–∞–∑ –≤ —Å–ª—É—á–∞–µ –æ—à–∏–±–∫–∏.

            –ï—Å–ª–∏ `success = true`, —Ç–æ –∑–Ω–∞—á–µ–Ω–∏–µ –≤—Å–µ–≥–¥–∞ `retryable = false`.
            –ï—Å–ª–∏ `success = false`, —Ç–æ:
            1. `retryable = true`, –µ—Å–ª–∏ –ø—Ä–∏–Ω–∏–º–∞—é—â–∞—è —Å–∏—Å—Ç–µ–º–∞ –î–û–õ–ñ–ù–ê –ø–æ–ø—Ä–æ–±–æ–≤–∞—Ç—å –≤—ã–≥—Ä—É–∑–∏—Ç—å –¥–∞–Ω–Ω—ã–π –æ–±—ä–µ–∫—Ç –ø–æ–≤—Ç–æ—Ä–Ω–æ —á–µ—Ä–µ–∑ –≤—Ä–µ–º—è (–Ω–∞–ø—Ä–∏–º–µ—Ä, –µ—Å–ª–∏ –Ω–∞ –ø—Ä–∏–Ω–∏–º–∞—é—â–µ–π —Å—Ç–æ—Ä–æ–Ω–µ –ø—Ä–æ–∏–∑–æ—à–ª–∞ –æ—à–∏–±–∫–∞ –æ–±—Ä–∞—â–µ–Ω–∏—è –∫ –≤–Ω–µ—à–Ω–µ–º—É —Å–µ—Ä–≤–µ—Ä—É –∏–ª–∏ –∫ –ë–î)
            2. `retryable = false`, –µ—Å–ª–∏ –ø—Ä–∏–Ω–∏–º–∞—é—â–∞—è —Å–∏—Å—Ç–µ–º–∞ –ù–ï –î–û–õ–ñ–ù–ê –≤—ã–ø–æ–ª–Ω—è—Ç—å –ø–æ–≤—Ç–æ—Ä–Ω—ã–µ –ø–æ–ø—ã—Ç–∫–∏ –≤—ã–≥—Ä—É–∑–∫–∏ –¥–∞–Ω–Ω–æ–π —Å—É—â–Ω–æ—Å—Ç–∏ (–Ω–∞–ø—Ä. –ø–æ–ª—è –≤ —Å—É—â–Ω–æ—Å—Ç–∏ —É–∫–∞–∑–∞–Ω—ã –Ω–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω–æ –∏ –ø–æ–≤—Ç–æ—Ä–Ω—ã–µ –ø–æ–ø—ã—Ç–∫–∏ –≤—ã–≥—Ä—É–∑–∫–∏ —Ç–∞–∫–æ–≥–æ –æ–±—ä–µ–∫—Ç–∞ –Ω–∏–∫–æ–≥–¥–∞ –Ω–µ –ø—Ä–∏–≤–µ–¥—É—Ç –∫ —É—Å–ø–µ—à–Ω–æ–º—É —Ä–µ–∑—É–ª—å—Ç–∞—Ç—É)
          example: false
        error:
          $ref: '#/components/schemas/ErrorResponseDto'
      required:
        - id
        - success
    Icd10WithAdditionalCodes:
      title: Icd10WithAdditionalCodes
      type: object
      description: –ú–ö–ë-10 + —Ç–æ–ø–æ–≥—Ä–∞—Ñ–∏—á–µ—Å–∫–∏–π, –º–æ—Ä—Ñ–æ–ª–æ–≥–∏—á–µ—Å–∫–∏–π –∫–æ–¥—ã, —Ö–∞—Ä–∞–∫—Ç–µ—Ä –ø—Ä–æ—Ü–µ—Å—Å–∞ –∏ —Ç–∏–ø –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏—è
      properties:
        icd10:
          $ref: '#/components/schemas/DictionaryRef'
          description: –ö–æ–¥ –ú–ö–ë-10
        topographicalIcdO:
          $ref: '#/components/schemas/DictionaryRef'
          description: –¢–æ–ø–æ–≥—Ä–∞—Ñ–∏—á–µ—Å–∫–∏–π –ú–ö–ë-–û –∫–æ–¥
        morphologicalIcdO:
          $ref: '#/components/schemas/DictionaryRef'
          description: –ú–æ—Ä—Ñ–æ–ª–æ–≥–∏—á–µ—Å–∫–∏–π –ú–ö–ë-–û –∫–æ–¥
        processNature:
          $ref: '#/components/schemas/DictionaryRef'
          description: –¢–∏–ø –ø—Ä–æ—Ü–µ—Å—Å–∞
        tnmClassification:
          type: string
          description: –ö–ª–∞—Å—Å–∏—Ñ–∏–∫–∞—Ü–∏—è TNM
      required:
        - icd10
    UpsertPacsMedicalReportDto:
      title: UpsertPacsMedicalReportDto
      type: object
      description: –°–æ–∑–¥–∞–Ω–∏–µ/–æ–±–Ω–æ–≤–ª–µ–Ω–∏–µ –º–µ–¥–∏—Ü–∏–Ω—Å–∫–∏—Ö –∑–∞–∫–ª—é—á–µ–Ω–∏–π –≤ PACS OneCell
      properties:
        macroDescription:
          type: string
          description: –ú–∞–∫—Ä–æ–æ–ø–∏—Å–∞–Ω–∏–µ (–±—É–¥–µ—Ç –æ–±–Ω–æ–≤–ª–µ–Ω–æ –≤ –º–µ–¥. —Å–ª—É—á–∞–µ)
          pattern: ^(?!\s*$).+
        microDescription:
          type: string
          description: –ú–∏–∫—Ä–æ–æ–ø–∏—Å–∞–Ω–∏–µ
          pattern: ^(?!\s*$).+
        report:
          type: string
          description: –ó–∞–∫–ª—é—á–µ–Ω–∏–µ
          pattern: ^(?!\s*$).+
        comment:
          type: string
          description: –î–æ–ø. –∑–∞–º–µ—á–∞–Ω–∏—è –∏ —Ä–µ–∫–æ–º–µ–Ω–¥–∞—Ü–∏–∏
          pattern: ^(?!\s*$).+
        complexity:
          type: integer
          description: –ö–∞—Ç–µ–≥–æ—Ä–∏—è —Å–ª–æ–∂–Ω–æ—Å—Ç–∏
          minimum: 1
          maximum: 5
        icd10:
          $ref: '#/components/schemas/DictionaryRef'
        icd10DetailedList:
          type: array
          description: –ü–æ–ª–µ –æ–±—è–∑–∞—Ç–µ–ª—å–Ω–æ, –µ—Å–ª–∏ `icd10` –Ω–µ —É–∫–∞–∑–∞–Ω–æ
          items:
            $ref: '#/components/schemas/Icd10WithAdditionalCodes'
        morphologyCode:
          $ref: '#/components/schemas/DictionaryRef'
        doctorId:
          $ref: '#/components/schemas/UserRef'
        consultantId:
          $ref: '#/components/schemas/UserRef'
        ihcResult:
          type: string
          description: –†–µ–∑—É–ª—å—Ç–∞—Ç –ò–ì–•
          pattern: ^(?!\s*$).+
        additionalResearchResult:
          type: string
          description: –†–µ–∑—É–ª—å—Ç–∞—Ç –¥–æ–ø. –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏–π
          pattern: ^(?!\s*$).+
        signed:
          type: boolean
          description: –§–∞–∫—Ç –ø–æ–¥–ø–∏—Å–∞–Ω–∏—è –∑–∞–∫–ª—é—á–µ–Ω–∏—è (–≤–∞–ª–∏–¥–∞—Ü–∏–∏). –î–ª—è –æ—Ç–º–µ–Ω—ã –≤–∞–ª–∏–¥–∞—Ü–∏–∏ –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –æ—Ç–ø—Ä–∞–≤–∏—Ç—å –≤–µ—Å—å –æ–±—ä–µ–∫—Ç –∑–∞–∫–ª—é—á–µ–Ω–∏—è —Å —É—Å—Ç–∞–Ω–æ–≤–ª–µ–Ω–Ω—ã–º –∑–Ω–∞—á–µ–Ω–∏–µ–º `signed=false`
        signedAt:
          type: string
          format: date-time
          description: –í—Ä–µ–º—è –ø–æ–¥–ø–∏—Å–∞–Ω–∏—è –∑–∞–∫–ª—é—á–µ–Ω–∏—è (–≤–∞–ª–∏–¥–∞—Ü–∏–∏). –ú–æ–∂–µ—Ç –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å—Å—è –¥–ª—è —Ä–∞—Å—á—ë—Ç–∞ –æ—Å—Ç–∞–≤—à–µ–≥–æ—Å—è –≤—Ä–µ–º–µ–Ω–∏, –≤ —Ç–µ—á–µ–Ω–∏–µ –∫–æ—Ç–æ—Ä–æ–≥–æ –¥–æ—Å—Ç—É–ø–Ω–∞ –æ—Ç–º–µ–Ω–∞ –≤–∞–ª–∏–¥–∞—Ü–∏–∏ –∑–∞–∫–ª—é—á–µ–Ω–∏—è.
        locked:
          type: boolean
          description: –§–∞–∫—Ç –±–ª–æ–∫–∏—Ä–æ–≤–∏ —Ä–µ–¥–∞–∫—Ç–∏—Ä–æ–≤–∞–Ω–∏—è –∑–∞–∫–ª—é—á–µ–Ω–∏—è.  –ï—Å–ª–∏ `true`, —Ä–µ–¥–∞–∫—Ç–∏—Ä–æ–≤–∞–Ω–∏–µ –∑–∞–∫–ª—é—á–µ–Ω–∏—è –≤ –∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å–µ PACS OneCell –±—É–¥–µ—Ç –∑–∞–±–ª–æ–∫–∏—Ä–æ–≤–∞–Ω–æ. –î–ª—è –æ—Ç–º–µ–Ω—ã –±–ª–æ–∫–∏—Ä–æ–≤–∫–∏ –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –≤—ã–≥—Ä—É–∑–∏—Ç—å –∑–∞–∫–ª—é—á–µ–Ω–∏–µ –∏–∑ LIS –≤ PACS —Å–æ –∑–Ω–∞—á–µ–Ω–∏–µ–º `locked=false`
      required:
        - doctorId
        - signed
    ResearchRequestSlide:
      title: ResearchRequestSlide
      type: object
      description: |-
        –°–ª–∞–π–¥ –≤ —Ä–∞–º–∫–∞—Ö –ó–∞–ø—Ä–æ—Å–∞ –Ω–∞ –î–æ–∑–∞–∫–∞–∑ (–°–ª–∞–π–¥ –≤ –ó–Ω–î)

        üÜï–î–æ–±–∞–≤–ª–µ–Ω–æ –≤ –≤–µ—Ä—Å–∏–∏ API 1.10
      properties:
        researchRequestSlideId:
          type: string
          description: –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä **–°–ª–∞–π–¥–∞ –≤ –ó–Ω–î**. –£–Ω–∏–∫–∞–ª—å–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –¥–ª—è –∫–∞–∂–¥–æ–≥–æ **–°–ª–∞–π–¥–∞ –≤ –ó–Ω–î** –≤ —Ä–∞–º–∫–∞—Ö –æ–¥–Ω–æ–≥–æ –º–µ–¥—É—á—Ä–µ–∂–¥–µ–Ω–∏—è. –í—Å–µ–≥–¥–∞ –∏–º–µ–µ—Ç –ø—Ä–µ—Ñ–∏–∫—Å `rrs-`. –ù–µ –ø—É—Ç–∞–π—Ç–µ —Å –ø–æ–ª–µ–º `researchRequestId`. –ì–µ–Ω–µ—Ä–∏—Ä—É–µ—Ç—Å—è –≤ OneCell.
          pattern: ^rrs-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
          example: rrs-bb43d2bc-45b1-4736-a470-cee8e788af61
        slideId:
          type: string
          description: –£–Ω–∏–∫–∞–ª—å–Ω—ã–π –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å—Ç–µ–∫–ª–∞ –≤ —Ä–∞–º–∫–∞—Ö —Å–ª—É—á–∞—è. –ù–∞–ø—Ä–∏–º–µ—Ä, –Ω–æ–º–µ—Ä/—à—Ç—Ä–∏—Ö–∫–æ–¥ —Å—Ç–µ–∫–ª–∞. –£–∫–∞–∑—ã–≤–∞–µ—Ç—Å—è –≤ —Ç–∞–∫–æ–º –∂–µ —Ñ–æ—Ä–º–∞—Ç–µ, –∫–∞–∫ –∏ –ø—Ä–∏ –≤—ã–≥—Ä—É–∑–∫–µ —Å–ª—É—á–∞–µ–≤ –∏–∑ –õ–ò–° –≤ –ü–ê–ö–°.
          example: 5130-I22006394-1-2-3
          pattern: ^(?!\s*$).+
        blockId:
          type: string
          description: –£–Ω–∏–∫–∞–ª—å–Ω—ã–π –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä –±–ª–æ–∫–∞ –≤ —Ä–∞–º–∫–∞—Ö —Å–ª—É—á–∞—è. –ù–∞–ø—Ä–∏–º–µ—Ä, –Ω–æ–º–µ—Ä/—à—Ç—Ä–∏—Ö–∫–æ–¥ –±–ª–æ–∫–∞. –£–∫–∞–∑—ã–≤–∞–µ—Ç—Å—è –≤ —Ç–∞–∫–æ–º –∂–µ —Ñ–æ—Ä–º–∞—Ç–µ, –∫–∞–∫ –∏ –ø—Ä–∏ –≤—ã–≥—Ä—É–∑–∫–µ —Å–ª—É—á–∞–µ–≤ –∏–∑ –õ–ò–° –≤ –ü–ê–ö–°.
          example: 1-2
          pattern: ^(?!\s*$).+
        stain:
          $ref: '#/components/schemas/StainDictionaryRef'
          description: –û–∫—Ä–∞—Å–∫–∞, –∫–æ—Ç–æ—Ä–∞—è —Ç—Ä–µ–±—É–µ—Ç—Å—è –≤—Ä–∞—á—É.
      required:
        - researchRequestSlideId
    ResearchRequest:
      title: ResearchRequest
      type: object
      description: |-
        –ó–∞–ø—Ä–æ—Å –Ω–∞ –î–æ–∑–∞–∫–∞–∑

        üÜï–î–æ–±–∞–≤–ª–µ–Ω–æ –≤ –≤–µ—Ä—Å–∏–∏ API 1.10
      properties:
        researchRequestId:
          type: string
          description: –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä **–ó–Ω–î**. –£–Ω–∏–∫–∞–ª—å–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –¥–ª—è –∫–∞–∂–¥–æ–π **–ó–Ω–î** –≤ —Ä–∞–º–∫–∞—Ö –æ–¥–Ω–æ–≥–æ –º–µ–¥—É—á—Ä–µ–∂–¥–µ–Ω–∏—è. –í—Å–µ–≥–¥–∞ –∏–º–µ–µ—Ç –ø—Ä–µ—Ñ–∏–∫—Å `rr-`. –ù–µ –ø—É—Ç–∞–π—Ç–µ —Å –ø–æ–ª–µ–º `researchRequestSlideId`. –ì–µ–Ω–µ—Ä–∏—Ä—É–µ—Ç—Å—è –≤ OneCell.
          pattern: ^rr-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
          example: rr-96eafb9e-0b79-493e-b336-3142827db07e
        caseNumber:
          type: string
          description: –£–Ω–∏–∫–∞–ª—å–Ω—ã–π –Ω–æ–º–µ—Ä —Å–ª—É—á–∞—è
          example: B00000001
          pattern: ^(?!\s*$).+
        type:
          type: string
          description: |-
            –¢–∏–ø –¥–æ–∑–∞–∫–∞–∑–∞
            - –ü–µ—Ä–µ—Å–∫–∞–Ω–∏—Ä–æ–≤–∞–Ω–∏–µ —Å—Ç–µ–∫–ª–∞ `RESCAN`
            - –ü–µ—Ä–µ—Ä–µ–∑–∫–∞ `NEW_CUTS`
            - –ü–æ—Å–ª–µ–¥–æ–≤–∞—Ç–µ–ª—å–Ω—ã–µ —Å—Ä–µ–∑—ã `NEW_SERIAL_CUTS`
            - –ù–æ–≤–∞—è –æ–∫—Ä–∞—Å–∫–∞ –ì–• `NEW_STAIN_HC`
            - –ù–æ–≤–∞—è –æ–∫—Ä–∞—Å–∫–∞ –ò–ì–• `NEW_STAIN_IHC`
            - –ù–æ–≤–∞—è –æ–∫—Ä–∞—Å–∫–∞ –ò–ì–• (–æ—Ç–¥–µ–ª—å–Ω—ã–π —Å–ª—É—á–∞–π) `NEW_STAIN_IHC_NEW_CASE`
          example: NEW_SERIAL_CUTS
          enum:
            - RESCAN
            - NEW_CUTS
            - NEW_SERIAL_CUTS
            - NEW_STAIN_HC
            - NEW_STAIN_IHC
            - NEW_STAIN_IHC_NEW_CASE
        slides:
          type: array
          description: –ú–∞—Å—Å–∏–≤ —Å–ª–∞–π–¥–æ–≤ –≤ —Ä–∞–º–∫–∞—Ö –¥–æ–∑–∞–∫–∞–∑–∞
          items:
            $ref: '#/components/schemas/ResearchRequestSlide'
        preparationComment:
          type: string
          description: |-
            –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π –¥–ª—è –ø—Ä–æ–±–æ–ø–æ–¥–≥–æ—Ç–æ–≤–∫–∏.
            –°—é–¥–∞ –∂–µ –¥–æ–±–∞–≤–ª—è—é—Ç—Å—è –ø–∞—Ä–∞–º–µ—Ç—Ä—ã —Å–∫–∞–Ω–∏—Ä–æ–≤–∞–Ω–∏—è.
          pattern: ^(?!\s*$).+
          example: |-
            –ù–µ–æ–±—Ö–æ–¥–∏–º–æ –ø–æ–º–µ—Å—Ç–∏—Ç—å —Ç–∫–∞–Ω—å –Ω–∞ –¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ–º —Ä–∞—Å—Å—Ç–æ—è–Ω–∏–∏ –¥—Ä—É–≥ –æ—Ç –¥—Ä—É–≥–∞, —Ö–æ—Ç—è-–±—ã 5-7–º–º.
            –ü–∞—Ä–∞–º–µ—Ç—Ä—ã —Å–∫–∞–Ω–∏—Ä–æ–≤–∞–Ω–∏—è: 40x.
        newCaseRequested:
          type: boolean
          description: –£–∫–∞–∑—ã–≤–∞–µ—Ç—Å—è TRUE, –µ—Å–ª–∏ –¥–ª—è –°–ª—É—á–∞—è —Ç—Ä–µ–±—É–µ—Ç—Å—è —Å–æ–∑–¥–∞—Ç—å –¥–æ—á–µ—Ä–Ω–∏–π —Å–ª—É—á–∞–π –∏ –≤ –Ω–µ–º —É–∂–µ –≤—ã–ø–æ–ª–Ω–∏—Ç—å –î–æ–∑–∞–∫–∞–∑.
          example: false
        createdAt:
          type: string
          format: date-time
          description: –î–∞—Ç–∞ —Å–æ–∑–¥–∞–Ω–∏—è –¥–æ–∑–∞–∫–∞–∑–∞ –≤ —Å–∏—Å—Ç–µ–º–µ OneCell
          pattern: ^(?!\s*$).+
          example: '2024-09-17T13:38:27+00:00'
        doctorId:
          $ref: '#/components/schemas/UserRef'
          description: |-
            –ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å, –∫–æ—Ç–æ—Ä—ã–π —Å–æ–∑–¥–∞–ª –¥–æ–∑–∞–∫–∞–∑.

            –û–±—Ä–∞—Ç–∏—Ç–µ –≤–Ω–∏–º–∞–Ω–∏–µ, —á—Ç–æ –≤—Ä–∞—á –º–æ–∂–µ—Ç –±—ã—Ç—å –∏–∑ –¥—Ä—É–≥–æ–≥–æ WorkSpace, –µ—Å–ª–∏ –∑–∞–ø—Ä–æ—Å –ø—Ä–∏—à—ë–ª –∏–∑ —Å–≤—è–∑–∞–Ω–Ω–æ–π –ª–∞–±–æ—Ä–∞—Ç–æ—Ä–∏–∏.
            –í —Ç–∞–∫–æ–º —Å–ª—É—á–∞–µ, –≤ –ø–æ–ª–µ `doctorExternalWorkspaceId` –±—É–¥–µ—Ç —É–∫–∞–∑—ã–≤–∞—Ç—å—Å—è –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å–≤—è–∑–∞–Ω–Ω–æ–≥–æ WS.
        doctorExternalWorkspaceId:
          type: number
          format: int64
          description: |-
            –ï—Å–ª–∏ –≤—Ä–∞—á, –∫–æ—Ç–æ—Ä—ã–π —Å–æ–∑–¥–∞–≤–∞–ª –ó–Ω–î **–Ω–µ —Å–æ—Å—Ç–æ–∏—Ç –≤ WS —Å–ª—É—á–∞—è**, —Ç–æ –∑–¥–µ—Å—å —É–∫–∞–∑—ã–≤–∞–µ—Ç—Å—è ID WS, –∏–∑ –∫–æ—Ç–æ—Ä–æ–≥–æ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å —Å–æ–∑–¥–∞–≤–∞–ª –ó–Ω–î (–≤ —Å–ª—É—á–∞–µ, –∫–æ–≥–¥–∞ –ó–Ω–î —Å–æ–∑–¥–∞—ë—Ç—Å—è –¥–ª—è —Å–≤—è–∑–∞–Ω–Ω–æ–≥–æ WS).

            –ï—Å–ª–∏ –≤—Ä–∞—á **—Å–æ—Å—Ç–æ–∏—Ç –≤ WS —Å–ª—É—á–∞—è**, —Ç–æ –∑–Ω–∞—á–µ–Ω–∏–µ –≤—Å–µ–≥–¥–∞ –±—É–¥–µ—Ç NULL.
          example: 12
      required:
        - researchRequestId
        - caseNumber
        - type
        - slides
        - newCaseRequested
        - createdAt
        - doctorId
  responses:
    CaseSearchResponse:
      description: –†–µ–∑—É–ª—å—Ç–∞—Ç—ã –ø–æ–∏—Å–∫–∞
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/UpsertPacsCaseDto'
          examples:
            '–ü—Ä–∏–º–µ—Ä: –Ω–∞–π–¥–µ–Ω–æ 2 —Å–ª—É—á–∞—è –∏–∑ 3':
              value:
                - caseNumber: B00000001
                  orderNumber: '000000041'
                  caseDate: '2019-08-24T14:15:22Z'
                  patient:
                    patientId: PAT-01252155
                    fullname: –í–∞—Å–∏–ª–∏–π –ü—É–ø–∫–∏–Ω –û–ª–µ–≥–æ–≤–∏—á
                    birthDate: '1984-08-24'
                    sex: MALE
                  services:
                    - id: SVC-001
                      shortName: –ü–æ—Å—Ç–î–∏–∞–≥–Ω
                      name: –ü–æ—Å—Ç–∞–Ω–æ–≤–∫–∞ –¥–∏–∞–≥–Ω–æ–∑–∞
                  incomingIcd10:
                    id: '2951'
                    shortName: J39.2
                    name: –î—Ä—É–≥–∏–µ –±–æ–ª–µ–∑–Ω–∏ –≥–ª–æ—Ç–∫–∏
                  macroDescription: string
                  description: string
                  doctorId:
                    userIdentifier: string
                    fullname: string
                  materialTakeoutDate: '2019-08-24T14:15:22Z'
                  materialType:
                    id: string
                    shortName: string
                    name: string
                  diagnosticProcedureType:
                    id: string
                    shortName: string
                    name: string
                  caseResearchType:
                    id: string
                    shortName: string
                    name: string
                  comment: string
                  notes:
                    - noteId: string
                      author:
                        userIdentifier: string
                        fullname: string
                      createdAt: '2019-08-24T14:15:22Z'
                      body: string
                  bioMaterials:
                    - bioMaterialId: '1011021031'
                      bioMaterial: string
                      site:
                        id: string
                        shortName: string
                        name: string
                      processNature:
                        id: string
                        shortName: string
                        name: string
                      fragmentsCount: 0
                      blocksCount: 0
                      slidesCount: 0
                  blocks:
                    - blockId: string
                      site:
                        id: string
                        shortName: string
                        name: string
                  slides:
                    - slideId: string
                      blockId: string
                      stain:
                        id: string
                        shortName: string
                        name: string
                        stainType: HC
                        availableForOrder: false
                - caseNumber: B99999999
                  orderNumber: '000000171'
                  caseDate: '2019-08-24T14:15:22Z'
                  patient:
                    patientId: PAT-55121042
                    fullname: –û–ª—å–≥–∞ –û–ª—å–≥–æ–≤–Ω–∞ –û–ª–µ–≥–æ–≤–Ω–∞
                    birthDate: '1962-11-21'
                    sex: FEMALE
                  services:
                    - id: SVC-001
                      shortName: –ü–æ—Å—Ç–î–∏–∞–≥–Ω
                      name: –ü–æ—Å—Ç–∞–Ω–æ–≤–∫–∞ –¥–∏–∞–≥–Ω–æ–∑–∞
                  incomingIcd10:
                    id: string
                    shortName: string
                    name: string
                  macroDescription: string
                  description: string
                  doctorId:
                    userIdentifier: string
                    fullname: string
                  materialTakeoutDate: '2019-08-24T14:15:22Z'
                  materialType:
                    id: string
                    shortName: string
                    name: string
                  diagnosticProcedureType:
                    id: string
                    shortName: string
                    name: string
                  caseResearchType:
                    id: string
                    shortName: string
                    name: string
                  comment: string
                  notes:
                    - noteId: string
                      author:
                        userIdentifier: string
                        fullname: string
                      createdAt: '2019-08-24T14:15:22Z'
                      body: string
                  bioMaterials:
                    - bioMaterialId: '2223334445'
                      bioMaterial: string
                      site:
                        id: string
                        shortName: string
                        name: string
                      processNature:
                        id: string
                        shortName: string
                        name: string
                      fragmentsCount: 0
                      blocksCount: 0
                      slidesCount: 0
                  blocks:
                    - blockId: string
                      site:
                        id: string
                        shortName: string
                        name: string
                  slides:
                    - slideId: string
                      blockId: string
                      stain:
                        id: string
                        shortName: string
                        name: string
                        stainType: IHC
                        availableForOrder: true
                      researchRequestSlideId: rrs-bb43d2bc-45b1-4736-a470-cee8e788af61
                  researchRequestId: rr-96eafb9e-0b79-493e-b336-3142827db07e
    ErrorResponse:
      description: Error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseDto'
            description: ''
            x-examples:
              example-1:
                timestamp: '2021-11-12T15:47:13.130+00:00'
                status: 404
                error: Not Found
                exception: ai.onecell.service.filestorage.exceptions.BlobNotFoundException
                message: Blob is not found
                path: /v1/some-url
    BulkMethodResponse:
      description: –†–µ–∑—É–ª—å—Ç–∞—Ç –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è –≥—Ä—É–ø–ø–æ–≤–æ–π –æ–ø–µ—Ä–∞—Ü–∏–∏
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/OperationStatusDto'
          examples:
            example-1:
              value:
                - id: B0000001
                  success: true
                - id: B0000002
                  success: false
                  error:
                    code: VALIDATION_FAILED
                    message: –ù–µ–∫–æ—Ç–æ—Ä—ã–µ –ø–æ–ª—è –∑–∞–ø–æ–ª–Ω–µ–Ω—ã –Ω–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω–æ
                    fieldErrors:
                      - code: INVALID_SIZE
                        property: name
                        message: –ü–æ–ª–µ name –¥–æ–ª–∂–Ω–æ —Å–æ–¥–µ—Ä–∂–∞—Ç—å —Ö–æ—Ç—è-–±—ã 2 –±—É–∫–≤—ã
                        rejectedValue: a
                        path: person.name
    BulkMethodResponseWithRetry:
      description: –†–µ–∑—É–ª—å—Ç–∞—Ç –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è –≥—Ä—É–ø–ø–æ–≤–æ–π –æ–ø–µ—Ä–∞—Ü–∏–∏
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/OperationStatusDto'
          examples:
            example-1:
              value:
                - id: rr-96eafb9e-0b79-493e-b336-3142827db07e
                  success: true
                  retryable: false
                - id: rr-bcfe8f8e-ebb8-4231-bb2e-2f8da5a0a23d
                  success: false
                  retryable: true
                  error:
                    code: EMIAS_CONNECTION_FAILED
                    message: –û—à–∏–±–∫–∞ –ø–æ–¥–∫–ª—é—á–µ–Ω–∏—è –∫ –ï–ú–ò–ê–°. –ü–æ–∂–∞–ª—É–π—Å—Ç–∞, –ø–æ–≤—Ç–æ—Ä–∏—Ç–µ –ø–æ–ø—ã—Ç–∫—É –≤—ã–≥—Ä—É–∑–∫–∏ –ø–æ–∑–¥–Ω–µ–µ
                    fieldErrors: []
                - id: rr-75ee5242-ddbf-4afa-8f93-b9f6f8c95aca
                  success: false
                  retryable: false
                  error:
                    code: VALIDATION_FAILED
                    message: –ù–µ–∫–æ—Ç–æ—Ä—ã–µ –ø–æ–ª—è –∑–∞–ø–æ–ª–Ω–µ–Ω—ã –Ω–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω–æ
                    fieldErrors:
                      - code: INVALID_SIZE
                        property: name
                        message: –ü–æ–ª–µ name –¥–æ–ª–∂–Ω–æ —Å–æ–¥–µ—Ä–∂–∞—Ç—å —Ö–æ—Ç—è-–±—ã 2 –±—É–∫–≤—ã
                        rejectedValue: a
                        path: person.name
